# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
# SPDX-FileCopyrightText: 2019 Maximilian Falkenstein <falkensm@ethz.ch>
exclude: '^.*\.patch$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/doublify/pre-commit-clang-format
    rev: fa51c34fccdd17b4297ba66269ee680094f4c91b
    hooks:
    -   id: clang-format
        exclude: src/tools/*
